---

  - name: updating /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ hostvars[item].ansible_template_host }} {{ item }} {{ item }}.{{ root_host_domain }}"
      line: "{{ hostvars[item].ansible_template_host }} {{ item }} {{ item }}.{{ root_host_domain }}"
      state: present
    with_items: "{{ groups['all'] }}"
